### ISSUE TITLE
/path/to/tmpdirectory overwrites sites from other projects

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-ghpages#11]
## steps

Follow README and make a minimal project without name or organization set:

```scala
import com.typesafe.sbt.site.PamfletSupport._

lazy val root = (project in file("."))
  .settings(
    site.settings,
    site.pamfletSupport(),
    ghpages.settings,
    git.remoteRepo := "git@github.com:sbt/sbt.github.com.git"
  )
```

Publish to gh-pages. Let's call this `scala-sbt.org`.

Make another project with different content. `baz.com`.
Publish to gh-pages.

## problem

The content of `baz.com` is published to `scala-sbt.org`.

## expectation

1. The content of `baz.com` is published to `baz.com`.
2. If `organization` and `name` are used, document it on README.
3. Detect collision in some way and warn the user.

## notes

`/path/to/tmpdirectory` mentioned in the README is actually

```scala
repository <<= (name,organization) apply ((n,o) => file(System.getProperty("user.home")) / ".sbt" / "ghpages" / o / n),      
```

In my case both bar.com and baz.com would have `~/.sbt/ghpages/root/root`.

**Comment by jsuereth** [comment]
0.5.4 should fix this issue.

**Comment by eed3si9n** [comment]
:fireworks:
