### ISSUE TITLE
Release missing for v0.8.0

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-ghpages#125]
* https://github.com/sbt/sbt-ghpages/releases/tag/v0.7.0 :heavy_check_mark: 
* https://github.com/sbt/sbt-ghpages/releases/tag/v0.8.0 :heavy_multiplication_x: 

/cc @eed3si9n

**Comment by eed3si9n** [comment]
I don't know who tagged this one, but here it is - https://github.com/sbt/sbt-ghpages/releases/tag/v0.8.0
