### ISSUE TITLE
sbt-ghpages conflict with sbt-ci-release plugin due to sbt-git uncompatible version

### ISSUE THREAD

**Issue by RustedBones** [sbt/sbt-ghpages#85]
`sbt-ci-release` v1.5.11  moved to `sbt-git`  2.0.0 which is published under another org
```
com.typesafe.sbt.GitPlugin > com.github.sbt.GitPlugin
```

Currently it creates keys conflict:

```log
[error] Some keys were defined with the same name but different types: 'gitReader' (com.typesafe.sbt.git.ReadableGit, com.github.sbt.git.ReadableGit), 'gitRunner' (sbt.Task[com.typesafe.sbt.git.GitRunner], sbt.Task[com.github.sbt.git.GitRunner])
```

`sbt-ghpages` needs a new release containing https://github.com/sbt/sbt-ghpages/commit/09aa28a089b8748abe1598976620c7b280880caa so we can use both plugins togethed

**Comment by RustedBones** [comment]
maybe @xuwei-k since you did the last releases ?

**Comment by xuwei-k** [comment]
I think we should change `groupId` to `com.github.sbt` from `com.typesafe.sbt` and publish to maven central by sbt-ci-release like another plugins.

- https://github.com/sbt/sbt-release/issues/271


@eed3si9n Could you set credentials? 🙏 

https://github.com/sbt/sbt-ghpages/settings/secrets/actions

**Comment by eed3si9n** [comment]
Sorry about the delay. The credentials are now set.

**Comment by xuwei-k** [comment]
Thanks!. I'll change build settings and release new version.

**Comment by xuwei-k** [comment]
0.7.0 released
